set mode MySQL;

--drop table if exists statistics_request;
--drop table if exists statistics_endpoint;
--drop table if exists payment;
--drop table if exists users;

create table if not exists users (
    id int generated by default as identity primary key,
    username varchar(255) unique not null,
    hashed_password varchar(255) not null,
    balance numeric(10,4) not null
);

create table if not exists payment (
    id int generated by default as identity primary key,
    user_id int not null,
    payment_time timestamp not null default current_timestamp(),
    amount numeric(10,4) not null,
    constraint fk_payment_user foreign key (user_id) references users(id)
);

create table if not exists statistics_endpoint (
    id int generated by default as identity primary key,
    endpoint varchar(255) unique not null,
    price numeric(10,4) not null
);

create table if not exists statistics_request (
    id int generated by default as identity primary key,
    user_id int not null,
    endpoint_id int not null,
    request_time timestamp not null default current_timestamp(),
    price numeric(10,4) not null,
    constraint fk_request_user foreign key (user_id) references users(id),
    constraint fk_request_endpoint foreign key (endpoint_id) references statistics_endpoint(id)
);
